const Data=  [
    {"country_id":"1","sortname":"AF","country_name":"Afghanistan","states":[
     {"state_id":"42","state_name":"Badakhshan","country_id":"1"},
     {"state_id":"43","state_name":"Badgis","country_id":"1"},
     {"state_id":"44","state_name":"Baglan","country_id":"1"},
     {"state_id":"45","state_name":"Balkh","country_id":"1"},
     {"state_id":"46","state_name":"Bamiyan","country_id":"1"},
     {"state_id":"47","state_name":"Farah","country_id":"1"},
     {"state_id":"48","state_name":"Faryab","country_id":"1"},
     {"state_id":"49","state_name":"Gawr","country_id":"1"},
     {"state_id":"50","state_name":"Gazni","country_id":"1"},
     {"state_id":"51","state_name":"Herat","country_id":"1"},
     {"state_id":"52","state_name":"Hilmand","country_id":"1"},
     {"state_id":"53","state_name":"Jawzjan","country_id":"1"},
     {"state_id":"54","state_name":"Kabul","country_id":"1"},
     {"state_id":"55","state_name":"Kapisa","country_id":"1"},
     {"state_id":"56","state_name":"Khawst","country_id":"1"},
     {"state_id":"57","state_name":"Kunar","country_id":"1"},
     {"state_id":"58","state_name":"Lagman","country_id":"1"},
     {"state_id":"59","state_name":"Lawghar","country_id":"1"},
     {"state_id":"60","state_name":"Nangarhar","country_id":"1"},
     {"state_id":"61","state_name":"Nimruz","country_id":"1"},
     {"state_id":"62","state_name":"Nuristan","country_id":"1"},
     {"state_id":"63","state_name":"Paktika","country_id":"1"},
     {"state_id":"64","state_name":"Paktiya","country_id":"1"},
     {"state_id":"65","state_name":"Parwan","country_id":"1"},
     {"state_id":"66","state_name":"Qandahar","country_id":"1"},
     {"state_id":"67","state_name":"Qunduz","country_id":"1"},
     {"state_id":"68","state_name":"Samangan","country_id":"1"},
     {"state_id":"69","state_name":"Sar-e Pul","country_id":"1"},
     {"state_id":"70","state_name":"Takhar","country_id":"1"},
     {"state_id":"71","state_name":"Uruzgan","country_id":"1"},
     {"state_id":"72","state_name":"Wardag","country_id":"1"},
     {"state_id":"73","state_name":"Zabul","country_id":"1"}

    ]},
    {"country_id":"101","sortname":"IN","country_name":"India",
    "states":[
{"state_id":"1","state_name":"Andaman and Nicobar Islands","country_id":"101"},
{"state_id":"2","state_name":"Andhra Pradesh","country_id":"101"},
{"state_id":"3","state_name":"Arunachal Pradesh","country_id":"101"},
{"state_id":"4","state_name":"Assam","country_id":"101"},
{"state_id":"5","state_name":"Bihar","country_id":"101"},
{"state_id":"6","state_name":"Chandigarh","country_id":"101"},
{"state_id":"7","state_name":"Chhattisgarh","country_id":"101"},
{"state_id":"8","state_name":"Dadra and Nagar Haveli","country_id":"101"},
{"state_id":"9","state_name":"Daman and Diu","country_id":"101"},
{"state_id":"10","state_name":"Delhi","country_id":"101"},
{"state_id":"11","state_name":"Goa","country_id":"101"},
{"state_id":"12","state_name":"Gujarat","country_id":"101"},
{"state_id":"13","state_name":"Haryana","country_id":"101"},
{"state_id":"14","state_name":"Himachal Pradesh","country_id":"101"},
{"state_id":"15","state_name":"Jammu and Kashmir","country_id":"101"},
{"state_id":"16","state_name":"Jharkhand","country_id":"101"},
{"state_id":"17","state_name":"Karnataka","country_id":"101"},
{"state_id":"18","state_name":"Kenmore","country_id":"101"},
{"state_id":"19","state_name":"Kerala","country_id":"101"},
{"state_id":"20","state_name":"Lakshadweep","country_id":"101"},
{"state_id":"21","state_name":"Madhya Pradesh","country_id":"101"},
{"state_id":"22","state_name":"Maharashtra","country_id":"101"},
{"state_id":"23","state_name":"Manipur","country_id":"101"},
{"state_id":"24","state_name":"Meghalaya","country_id":"101"},
{"state_id":"25","state_name":"Mizoram","country_id":"101"},
{"state_id":"26","state_name":"Nagaland","country_id":"101"},
{"state_id":"27","state_name":"Narora","country_id":"101"},
{"state_id":"28","state_name":"Natwar","country_id":"101"},
{"state_id":"29","state_name":"Odisha","country_id":"101"},
{"state_id":"30","state_name":"Paschim Medinipur","country_id":"101"},
{"state_id":"31","state_name":"Pondicherry","country_id":"101"},
{"state_id":"32","state_name":"Punjab","country_id":"101"},
{"state_id":"33","state_name":"Rajasthan","country_id":"101"},
{"state_id":"34","state_name":"Sikkim","country_id":"101"},
{"state_id":"35","state_name":"Tamil Nadu","country_id":"101"},
{"state_id":"36","state_name":"Telangana","country_id":"101"},
{"state_id":"37","state_name":"Tripura","country_id":"101"},
{"state_id":"38","state_name":"Uttar Pradesh","country_id":"101"},
{"state_id":"39","state_name":"Uttarakhand","country_id":"101"},
{"state_id":"40","state_name":"Vaishali","country_id":"101"},
{"state_id":"41","state_name":"West Bengal","country_id":"101"}
    ]

    },
    {"country_id":"246","sortname":"ZW","country_name":"Zimbabwe","states":[
        {"state_id":"4111","state_name":"Bulawayo","country_id":"246"},
   {"state_id":"4112","state_name":"Harare","country_id":"246"},
   {"state_id":"4113","state_name":"Manicaland","country_id":"246"},
   {"state_id":"4114","state_name":"Mashonaland Central","country_id":"246"},
   {"state_id":"4115","state_name":"Mashonaland East","country_id":"246"},
   {"state_id":"4116","state_name":"Mashonaland West","country_id":"246"},
   {"state_id":"4117","state_name":"Masvingo","country_id":"246"},
   {"state_id":"4118","state_name":"Matabeleland North","country_id":"246"},
   {"state_id":"4119","state_name":"Matabeleland South","country_id":"246"},
   {"state_id":"4120","state_name":"Midlands","country_id":"246"}
       ]}
   ]


export default Data